### ISSUE TITLE
When adding new patches feature vector will error

### ISSUE THREAD

**Issue by choosehappy** [choosehappy/PatchSorter#13]
There should be a different logic here
if feats isn't the right size, then delete it (this prevents the error)
if feats doesn't exist then create it and append
else assign

https://github.com/choosehappy/PatchSorter/blob/a6bc5aa2ac40e5803054830dc5cb0317943b67dc/approaches/simclr/make_embed_simclr.py#L189

```
2023-02-13 15:22:59,884 - jobs - [DEBUG] (THREAD 140249329448768) ERROR: Traceback (most recent call last):	  File "./approaches/simclr/make_embed_simclr.py", line 196, in <module>	    db.root.feats[:] = all_vecs_full	  File "/usr/local/lib/python3.8/dist-packages/tables/array.py", line 726, in __setitem__	    self._write_slice(startl, stopl, stepl, shape, nparr)	  File "/usr/local/lib/python3.8/dist-packages/tables/array.py", line 806, in _write_slice	    nparr = self._check_shape(nparr, tuple(shape))	  File "/usr/local/lib/python3.8/dist-packages/tables/array.py", line 750, in _check_shape	    narr[...] = nparr	ValueError: could not broadcast input array from shape (1206,256) into shape (1033,256)
```

**Comment by choosehappy** [comment]
something like this should do it, but needs to be tested:

```python
if hasattr(db.root, 'feats')  and (db.root.feats.shape[1]!=all_vecs_full.shape[1]):
      db.root.feats.remove()

if not hasattr(db.root, 'feats'):
    dim = args.dimredux if args.dimredux > 0 else args.codesize
    db.create_earray(db.root, "feats", tables.Float16Atom(), shape=np.append([0], dim),
                     chunkshape=np.append([1], dim),
                     filters=tables.Filters(complevel=6, complib='zlib'))
    db.root.feats.append(all_vecs_full)
else:
    db.root.feats[:] = all_vecs_full

```
